### PR TITLE
Py design

### PR DESCRIPTION
**Pull request by ryanmrichard**
**PR Type**

- [ ] Breaking change
- [x] Feature
- [ ] Patch

**Brief Description**

This adds some notes I took while working out the Python design.

**Not In Scope**

N/A

**PR Checklist**

- [x] [Is documented](https://nwchemex-project.github.io/.github/documenting/index.html)
- [x] [Is tested](https://nwchemex-project.github.io/.github/testing/index.html)
- [x] [Adheres to applicable organization standards](https://nwchemex-project.github.io/.github/conventions/index.html)

### CODE REVIEW

**Comment by ryanmrichard** [comment]
In preparation for Thursday's discussions I started some design notes which reflect the status of the pybind11 bindings and where I see things going. If you get a chance, feel free to start discussing what's there prior to Thursday.

**Comment by ryanmrichard** [comment]
@jwaldrop107 can you review this so it can be merged?

**Review by jwaldrop107 — APPROVED** [review]
LGTM

**Comment by ryanmrichard** [comment]
🚀 [[bumpr]](https://github.com/haya14busa/action-bumpr) [Bumped!](https://github.com/NWChemEx-Project/.github/actions/runs/5313957533) **New version**:[v0.3.6](https://github.com/NWChemEx-Project/.github/releases/tag/v0.3.6) **Changes**:[v0.3.5...v0.3.6](https://github.com/NWChemEx-Project/.github/compare/v0.3.5...v0.3.6)

**Pull request merged**
